### ISSUE TITLE
Generate Scaladoc using Scala 2.12 tool

### ISSUE THREAD

**Issue by janekdb** [scala/scala-parser-combinators#104]
The generated Scaladoc was much improved in 2.12. It would be good to have this here.

**Comment by gourlaysama** [comment]
It does: http://www.scala-lang.org/api/current/scala-parser-combinators/scala/index.html

My guess is that you ran `doc` in sbt, which uses the first version in `crossScalaVersion`, so you got the 2.11 scaladoc.

Running `+doc` gives you the 2.12 version in `jvm/target/scala-2.12/api'.

**Comment by gourlaysama** [comment]
(I did wonder for a second how you got the old scaladoc in your PR snapshot)

**Comment by janekdb** [comment]
Thanks for the tip.
