### ISSUE TITLE
README should discuss branching situation

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#105]
there's a `1.0.x` branch and a `master` branch. at one time I knew how they were different, but now I've forgotten. could this be covered in the readme...?

in particular, I'm wondering which one we should be tracking in the Scala community build. (currently we are tracking `master`.)

**Comment by sjrd** [comment]
Is 1.0.x even still relevant?

**Comment by SethTisue** [comment]
note that `1.0.x` is currently the default branch

**Comment by SethTisue** [comment]
@gourlaysama this might be an easy one for you to address and close out...?

**Comment by SethTisue** [comment]
1.1.x is the default branch now

**Comment by SethTisue** [comment]
the `master` branch no longer exists, and the community build tracks `1.1.x` now
