### ISSUE TITLE
support Scala 2.13.0-M1

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-parser-combinators#110]

**Comment by SethTisue** [comment]
coming soon. @lrytz is working on making some needed updates to the sbt-scala-modules plugin and tag-based publishing scripts

**Comment by SethTisue** [comment]
happening at #109. waiting on a Scala.js 0.6.16 release

**Comment by milessabin** [comment]
Scala.js 0.6.16 is available now ... can someone crank the handle?

**Comment by gourlaysama** [comment]
I just staged v1.0.6 with 2.13.0-M1 support.

The staging repositories are:
 - 2.12 and 2.13.0-M1: https://oss.sonatype.org/service/local/repositories/orgscala-lang-1420/content/
 - 2.11: https://oss.sonatype.org/service/local/repositories/orgscala-lang-1419/content/

**Comment by gourlaysama** [comment]
And the repositories have been promoted.

@milessabin v1.0.6 is on its way to maven central, and at https://oss.sonatype.org/content/repositories/staging/ in the meantime :)

**Comment by milessabin** [comment]
Awesome! Thank you!

**Comment by SethTisue** [comment]
> v1.0.6 is on its way to maven central

it's there
