### ISSUE TITLE
release for Scala 2.13.0-M2

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-parser-combinators#124]

**Comment by lrytz** [comment]
```
git tag -s -m "1.0.6 for 2.13.0-M2" v1.0.6#2.13.0-M2#8 65802b5c91798609f6ac4fca136365d61607c031
git push upstream v1.0.6#2.13.0-M2#8
```
Build running here: https://travis-ci.org/scala/scala-parser-combinators/builds/259264349

**Comment by lrytz** [comment]
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-js#scalajs-library_2.13.0-M2;0.6.16: not found
[warn] 	:: org.scala-js#scalajs-test-interface_2.13.0-M2;0.6.16: not found
[warn] 	:: org.scala-js#scalajs-junit-test-runtime_2.13.0-M2;0.6.16: not found
[warn] 	:: org.scala-js#scalajs-compiler_2.13.0-M2;0.6.16: not found
[warn] 	:: org.scala-js#scalajs-junit-test-plugin_2.13.0-M2;0.6.16: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

0.6.16 is not released against 2.13.0-M2, but 0.6.19 is there. So this requires an update to the `build.sbt`. I'm not sure if it's ok push a new commit on top of 65802b5c91798609f6ac4fca136365d61607c031 and tag that as v1.0.6#2.13.0-M2#8? That would be a tag that's not part of the 1.0.x branch (or any other branch).



We'll have to see. Maybe it's easier to wait

**Comment by milessabin** [comment]
This is blocking me releasing shapeless for 2.13.0-M2 ...

**Comment by SethTisue** [comment]
@lrytz seems fine to me

**Comment by lrytz** [comment]
http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13.0-M2/1.0.6/

Note that only the JVM version works, the _sjs0.6 jar is still empty in this release (https://github.com/scala/scala-parser-combinators/issues/119). This will be fixed in 1.0.7.

**Comment by milessabin** [comment]
I think that's still blocks me releasing. I would have branched and bumped the sjs version.

**Comment by lrytz** [comment]
I did bump the sjs version: https://github.com/scala/scala-parser-combinators/compare/v1.0.6...v1.0.6%232.13.0-M2%238

Why does it block you? The release is equivalent to what we had for 2.13.0-M1.

**Comment by milessabin** [comment]
Oh, sorry, I misunderstood. In that case why is the  _sjs0.6 jar empty?

In any case, I was wrong about this blocking a shapeless release :-)

**Comment by lrytz** [comment]
See https://github.com/scala/scala-parser-combinators/issues/119

**Comment by milessabin** [comment]
Gotcha ... thanks :-)
