### ISSUE TITLE
scalajs library for 1.0.6 is empty

### ISSUE THREAD

**Issue by justjoheinz** [scala/scala-parser-combinators#126]
The jar file for the scalajs version 1.0.6 is empty, aka does not contain the code, just a meta-inf and js properties file.

Version 1.0.5 is working fine.

**Comment by xuwei-k** [comment]
https://github.com/scala/scala-parser-combinators/issues/119

**Comment by SethTisue** [comment]
yup, duplicate of #119. there is not yet a 1.0.7 release with the fix
