### ISSUE TITLE
Release 1.1.0, with support for Scala 2.13.0-M3

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#138]
as we found out over at #136, neither 1.0.6 nor 1.0.7 can be published for Scala 2.13.0-M3, since M3 removes `PagedSeq` from stdlib

@gourlaysama the PR in question is #97, which was merged on master for an eventual 1.1.0 release, but not backported to 1.0.x

is it time to roll 1.1.0? or should we backport and roll 1.0.8? does binary compatibility forbid the backport?

what else would be in 1.1.0? I haven't really followed the 1.0.x vs master differences

**Comment by gourlaysama** [comment]
See #139.

> what else would be in 1.1.0? I haven't really followed the 1.0.x vs master differences

There is only one change in 1.1 right now I think: #38.
There is another previously reverted change that could be added there, but that can wait for an 1.1.1.

**Comment by SethTisue** [comment]
sounds good to me

**Comment by gourlaysama** [comment]
I have pushed the `v1.1.0` tag and manually tested the published artifacts from Sonatype (repos `orgscala-lang-1466`, `orgscala-lang-1467`). It works!

@SethTisue can you push to Maven Central?

**Comment by SethTisue** [comment]
I hit "close" and "release" in the Sonatype web UI on both staging repos, so the artifacts should be on their way to Maven Central.

**Comment by SethTisue** [comment]
artifacts are up at http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13.0-M3/1.1.0/

**Comment by gourlaysama** [comment]
Released https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.0! 🎉
