### ISSUE TITLE
scaladoc

### ISSUE THREAD

**Issue by EECOLOR** [scala/scala-parser-combinators#15]
It took me quite some time to find the scaladocs at http://www.scala-lang.org/files/archive/nightly/docs/parser-combinators/

Could you list it on the scala-lang.org page and provide it for the current release?

**Comment by SethTisue** [comment]
I'm on it.

**Comment by SethTisue** [comment]
I can't find anything here that was left undone. If I'm wrong, please comment.

**Comment by EECOLOR** [comment]
The original issue is fixed: http://www.scala-lang.org/documentation/api.html
