### ISSUE TITLE
unexpected success in parsing wrong input

### ISSUE THREAD

**Issue by icar-aose** [scala/scala-parser-combinators#161]
Here is a very simple grammar for parsing first order logic predicates in the form functor(arguments)

```
class FolParser extends JavaTokenParsers {
  def predicate : Parser[Any] = ident~"("~opt(term_list)~")"
  def term_list : Parser[Any] = repsep(term,",")
  def term  : Parser[Any] = constant | atom
  def constant : Parser[Any] = floatingPointNumber  |  stringLiteral
  def atom : Parser[Any] = ident  | "true"  | "false"
}
```
when trying with the following input
```
object TestFolParser extends FolParser {
  def main(args : Array[String]) = {
    println(parse(predicate,"ready(document) not"))
  }
}
```
it should return error because the "not" is not in the language and the predicate rule will end after the ")"

So why the parser terminates without errors and with the following output
```
[1.16] parsed: (((ready~()~Some(List(document)))~))
```

**Comment by tom--k** [comment]
Hi! Try `parseAll` instead of `parse` method...

**Comment by SethTisue** [comment]
please consult https://www.scala-lang.org/community/ for guidance on where to seek coding help
