### ISSUE TITLE
fix jdk6 build

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-parser-combinators#169]
Maven central and Bintray dropped TLS 1.1 support, require TSL 1.2. JDK6 does not support TLS 1.2.

- https://blog.sonatype.com/enhancing-ssl-security-and-http/2-support-for-central
- https://jfrog.com/knowledge-base/why-am-i-failing-to-work-with-jfrog-saas-service-with-tls-1-0-1-1/
- https://github.com/scala/scala-collection-compat/issues/77

**Comment by ashawley** [comment]
TLS 1.2 works in Oracle JDK6, just not in openjdk6, see https://github.com/scala/sbt-scala-module/issues/41

**Comment by xuwei-k** [comment]
use http instead of https? 🤔 
https://github.com/scala/scala-xml/pull/247
