### ISSUE TITLE
Relicense under Apache 2.0?

### ISSUE THREAD

**Issue by gourlaysama** [scala/scala-parser-combinators#176]
https://contributors.scala-lang.org/t/moving-to-the-apache-v2-0-license/1859

Scala-xml also went through the re-licensing  (scala/scala-xml#227). I guess it would make sense to be consistent here.

**Comment by SethTisue** [comment]
indeed!

**Comment by SethTisue** [comment]
marked as "good first issue" since the scala-xml PR already exists as a model for what needs to be done. no discussions/approvals/decisions needed, only follow-through on doing the changes.

**Comment by SethTisue** [comment]
fixed by @sudohalt in #184
