### ISSUE TITLE
expand maintainer team?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#186]
@gourlaysama you've been fairly scarce lately, could you use some help?

I've merged some PRs myself, especially if they have to do with stuff that's common to all the Scala modules (build, CI, license, etc), but I can't really afford to get very involved with actual code changes

@Philippus would you be interested in getting more involved? (we can discuss here, or you can email me privately if you like, seth.tisue@lightbend.com)

and/or, we could put a call out via contributors.scala-lang.org and other online channels

**Comment by SethTisue** [comment]
ping @Philippus :-)

**Comment by Philippus** [comment]
I'd be happy to help out.

**Comment by SethTisue** [comment]
@Philippus awesome! ❤️

I've added you to https://github.com/orgs/scala/teams/maintainers/members

you may add yourself to https://github.com/scala/scala-parser-combinators/blob/1.1.x/README.md

we don't really have proper docs on module maintenance, but we do at least have a ticket where we collect notes toward such docs: https://github.com/scala/sbt-scala-module/issues/16

and my remarks at https://github.com/scala/scala-swing/issues/76#issuecomment-385631590 apply here as well
