### ISSUE TITLE
move development to a new 1.2.x branch?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#188]
this came up at #166 and also at #163 

~~additionally, we might consider dropping support for Java 6 and 7, which would permit us to move the build to sbt 1; see https://github.com/scala/sbt-scala-module/issues/32~~

we might also drop support for Scala 2.11. I don't see a _strong_ reason to do that, but it would certainly simplify maintenance going forward

**Comment by SethTisue** [comment]
> additionally, we might consider dropping support for Java 6 and 7,

that part already happened, actually.

**Comment by Philippus** [comment]
I've created a new 1.2.x branch and made it the default.

**Comment by Philippus** [comment]
Regarding dropping support for scala 2.11 I don't think it's desirable. We want to support scala native which is tied to 2.11 according to https://www.scala-native.org/en/v0.3.8/user/sbt.html#scala-versions.
