### ISSUE TITLE
release another 1.1.x version?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#189]
this came up at https://github.com/scala/scala-parser-combinators/pull/180

separately, #188 asks about branching for 1.2.x

**Comment by SethTisue** [comment]
another reason to do a release is Scala Native, https://github.com/scala/scala-parser-combinators/issues/141

@lolgab if there were any difficulties releasing for Scala Native would you try to help?

@gourlaysama any objections to doing a release?

@Philippus would be interested in writing release notes and attempting the publishing?

**Comment by lolgab** [comment]
I'm glad to help if I can. I published My first artifact yesterday (scalacheck native) and seen this as indirect dependency of cats, published it too (I were in publishing mood :D). So, sorry for being rude and bot asking an official release before publishing.

**Comment by SethTisue** [comment]
no worries, I mean, this has been pending for ages and ages now. I think you did the right thing to get other projects moving.

**Comment by SethTisue** [comment]
another reason to do another 1.1.x release is to switch over to publishing from JDK 8 (though still building/testing on JDK 6 to ensure JDK 6 compatibility) from dependencies retrieved via https only, as per 
https://github.com/scala/sbt-scala-module/issues/41#issuecomment-469410390

**Comment by Philippus** [comment]
Release notes v1.1.2

Scala-parser-combinators 1.1.2 is now available!

Changes in this release:

#193 Scala 2.13.0-RC1 is now supported
#184 Update license to Apache 2.0
#180  Fix StackOverflowError in Page.latest
#179 Fix StackOverflowError in PagedSeq.fromString
#174 Re-add support for Scala native
#164 Support '\r' and '\r\n' line endings
#162 Add 'exception' operator

It is available for Scala 2.11, 2.12 and 2.13.0-RC1:

`libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2"`
And for Scala-js 0.6.x:

`libraryDependencies += "org.scala-lang.modules" %%% "scala-parser-combinators" % "1.1.2"`

A big thank you to everyone who contributed to this release!
According to git shortlog -sn --no-merges v1.1.0..v1.1.1, 6 people contributed to v1.1.2: Umayah Abdennabi, Philippus Baalman, Antoine Gourlay, Seth Tisue, Filip Ochnik, Sarunas Valaskevicius.

**Comment by SethTisue** [comment]
LGTM

**Comment by SethTisue** [comment]
1.1.2 release job isn't able to upload to Sonatype, let's dive into that on a separate ticket (#194)

**Comment by SethTisue** [comment]
1.1.2 building at https://travis-ci.org/scala/scala-parser-combinators/builds/516398114

**Comment by SethTisue** [comment]
inspected contents, all nine combos present (2.11/2.12/RC1 x JVM/sjs0.6/sjs1)

<img width="852" alt="Screen Shot 2019-04-05 at 11 13 05 PM" src="https://user-images.githubusercontent.com/161079/55659185-781a3480-57f8-11e9-9503-58ed41350c31.png">

hit "close" in web UI

hit "release"

now we watch https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13.0-RC1/1.1.2/

**Comment by SethTisue** [comment]
release notes: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2

**Comment by Philippus** [comment]
we should look at releasing this tag for scala native, but not today. :)
