### ISSUE TITLE
we're trying to release 1.1.2 but tag-based publishing is failing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#194]
v1.1.2 tag was pushed by @Philippus, https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2

but at https://travis-ci.org/scala/scala-parser-combinators/builds/516214537 we see

```
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[warn] CLIENT ERROR: 401 Unauthorized. Check your resolvers username and password.
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[error] java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar.asc was refused by the server: Unauthorized
```

**Comment by SethTisue** [comment]
Adriaan Moors   [17 minutes ago]
huh, any idea of what happened? I looked at the script and it looks fine to me

Seth Tisue   [14 minutes ago]
I don't have a guess yet. I'm only starting to investigate now.

Seth Tisue   [13 minutes ago]
we upgraded to sbt 1 since the last release, so maybe

```
-addSbtPlugin("com.typesafe.sbt" % "sbt-pgp" % "0.8.3") // only added when publishing, see build.sh
+addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.2-1") // only added when publishing, see build.sh```
```
is the culprit somehow


Seth Tisue   [12 minutes ago]
scala-parallel-collections published okay from sbt 1

Seth Tisue   [11 minutes ago]
https://github.com/scala/scala-parallel-collections/commit/633a2267e596dc78a16b300f7123da064d6ccae4 is the same as what scala-parser-combinators has afaict

eugene yokota   [9 minutes ago]
do you use access token for Sonatype OSS? (edited)

eugene yokota   [9 minutes ago]
because they changed the user name recently, I think


Seth Tisue   [7 minutes ago]
encrypted username/password https://github.com/scala/scala-parser-combinators/blob/1.1.x/.travis.yml#L13-L20


eugene yokota   [7 minutes ago]
yea it says 4 years ago


eugene yokota   [7 minutes ago]
so you might want to check https://oss.sonatype.org/#profile;User%20Token


eugene yokota   [6 minutes ago]
it used to be the same as Sonatype login name, but I recently noticed that the user name for the access token has changed


Seth Tisue   [6 minutes ago]
that sounds like a good tip. I set up scala-parallel-collections in March 2017, so that could be the difference  I guess. I will try regenerating that stuff


Seth Tisue   [4 minutes ago]
I don't see anything about tokens at https://oss.sonatype.org/#profile;Summary


Seth Tisue   [4 minutes ago]
I'm logged as the `lamp` user which is what we use for this stuff


eugene yokota   [4 minutes ago]
there's a weird pull down menu


eugene yokota   [4 minutes ago]
it should say "Summary"


Seth Tisue   [4 minutes ago]
yeah and there are no other choices on the menu


eugene yokota   [4 minutes ago]
mine shows "Summary" and "User Token"


Seth Tisue   [3 minutes ago]
I'll just redo what I did for scala-parallel-collections, seems highly likely that will fix it

**Comment by SethTisue** [comment]
the `admin/build.sh` differences between the scala-parallel-collections repo and this one are confusing. so I'm first trying changing nothing except re-encrypting `SONA_USER` and `SONA_PASS` (in c3d56e59ce76f73c881cef890395325c4601c776)

I pushed the test tag `v1.1.2-TEST1` which is building at https://travis-ci.org/scala/scala-parser-combinators/builds/516338173

hmm, no improvement

```
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[warn] CLIENT ERROR: 401 Unauthorized. Check your resolvers username and password.
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[error] java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-parser-combinators_2.13.0-RC1/1.1.2-TEST1/scala-parser-combinators_2.13.0-RC1-1.1.2-TEST1-sources.jar.asc was refused by the server: Unauthorized
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
[error] 	at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.upload(GigahorseUrlHandler.scala:191)
```

**Comment by SethTisue** [comment]
`admin/build.sh` is rather different in this repo from the scala-parallel-collections one, our `admin/build.sh` is modeled on scala-xml's

scala-xml published successfully today, so maybe I can look into what might be different there

**Comment by SethTisue** [comment]
I must have merged #190 without actually trying it. gah

**Comment by SethTisue** [comment]
> scala-xml published successfully today, so maybe I can look into what might be different there

gah, but scala-xml is still on sbt 0.13.x

**Comment by SethTisue** [comment]
idk though, I just don't understand why `SONATYPE_USER` and `SONATYPE_PASSWORD` stuff would be affected by any of these other changes

**Comment by eed3si9n** [comment]
Here's my take - https://github.com/scala/scala-parser-combinators/pull/196

**Comment by SethTisue** [comment]
I'm doing a test on the `v1.1.2-TEST4` tag now, I think the combination of #195 and #196 might do the trick

**Comment by SethTisue** [comment]
(I think it's #174 that was never tested)

**Comment by SethTisue** [comment]
`[info] 	published scala-parser-combinators_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.2/scala-parser-combinators_2.12-1.1.2-sources.jar.asc`

🎉 💯 🍺 🍾

**Comment by eed3si9n** [comment]
Nice.

**Comment by Philippus** [comment]
good sleuthing everyone!

**Comment by SethTisue** [comment]
being a module maintainer's tons of fun, we promise!
