### ISSUE TITLE
Release version 1.1.2 for Scala Native

### ISSUE THREAD

**Issue by Philippus** [scala/scala-parser-combinators#201]
follow-up of #189

**Comment by Philippus** [comment]
If we backport https://github.com/scala/scala-parser-combinators/pull/204 to the `1.1.x` branch we could hopefully easily do this?

**Comment by SethTisue** [comment]
seems plausible

**Comment by Philippus** [comment]
backported in #205

**Comment by Philippus** [comment]
Is it possible to create a v1.1.2 tag specifically for scala native so it will be staged in maven?

**Comment by SethTisue** [comment]
I'm not sure, maybe @lrytz knows... you might have to push a tag that stages more artifacts than necessary, and then we can delete the unwanted ones in the Sonatype web UI before hitting "release"

**Comment by SethTisue** [comment]
let's keep this separate from the 2.13.0-RC3 release, which I want to finish quickly

as per discussion on #214, I now understand that the way we do it in this repo is, you make a commit where `.travis.yml` is cut down to just the versions you want, add a tag like `v1.1.2#native` (everything after the `#` is ignored), and push the tag. (the commit doesn't need to be on any branch)

**Comment by SethTisue** [comment]
> `v1.1.2#native` (everything after the `#` is ignored)

er, as we found over at #214, `v1.1.2#native#8`

**Comment by Philippus** [comment]
After some fiddling around I managed to get it published to sonatype:

tag: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2%23native%238
build: https://travis-ci.org/scala/scala-parser-combinators/builds/544229401

**Comment by Philippus** [comment]
it's available!
