### ISSUE TITLE
Release for Scala 2.13.0-RC3

### ISSUE THREAD

**Issue by Philippus** [scala/scala-parser-combinators#214]
Tag [v1.1.2#2.13.0-RC3#8](https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2%232.13.0-RC3%238) has been created, @SethTisue can you pick it up from here?

**Comment by SethTisue** [comment]
yes

publishing job is https://travis-ci.org/scala/scala-parser-combinators/builds/538949185

**Comment by Philippus** [comment]
Looks like the scala native artifacts also got published, we could release those as well?

**Comment by SethTisue** [comment]
sure, I see them on Sonatype. I'm in the middle of closing and releasing the staging repos.

**Comment by SethTisue** [comment]
sigh, something went wrong — one `.asc` file ended up in a staging repo all by itself, and then the whole batch failed Sonatype's checks. can you delete and then re-push the tag?

**Comment by Philippus** [comment]
https://travis-ci.org/scala/scala-parser-combinators/builds/538967696

**Comment by SethTisue** [comment]
shouldn't the staging repos have contained artifacts for 2.13.0-RC3 only? there were tons of 11 and 12 artifacts too. including the Scala Native artifacts. which should have tipped me off, but I'm sleepy

going to bed now, I'll look at it in the morning. (I'm in Europe early for Scala Days.)

I'm having deja vu. did this also happen last time? I can't remember if it was in this repo, or a different module repo. any clue why the tag parsing stuff isn't doing the right thing?

**Comment by SethTisue** [comment]
yeah it did happen here last time: https://github.com/scala/scala-parser-combinators/issues/211#issuecomment-493488072

**Comment by SethTisue** [comment]
scala-xml has the same problem, https://github.com/scala/scala-xml/issues/311

**Comment by SethTisue** [comment]
oh okay, this is just how things work now, after #174. I got confused because some other modules still do it the old way

**Comment by SethTisue** [comment]
* commit: https://github.com/scala/scala-parser-combinators/commit/0df35a1bc93414d12c8b8a437eec3647d83f512a
* tag: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2%232.13.0-RC3
* job: https://travis-ci.org/scala/scala-parser-combinators/builds/539095436

**Comment by SethTisue** [comment]
hmm well that didn't work. it only published locally, not to Sonatype

**Comment by SethTisue** [comment]
It appears that contrary to the comment in `admin/build.sh`, the `#8` at the end is required after all, note the two appearances of `#` in `tagPat`

**Comment by SethTisue** [comment]
* commit: https://github.com/scala/scala-parser-combinators/commit/0df35a1bc93414d12c8b8a437eec3647d83f512a
* tag: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2%232.13.0-RC3%238
* job: https://travis-ci.org/scala/scala-parser-combinators/builds/539103324

**Comment by SethTisue** [comment]
staging repos closed, released.

now we keep an eye out at https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13.0-RC3/1.1.2/

**Comment by SethTisue** [comment]
scala/make-release-notes@725d20a5b3b0e70ebf53a3ef9fb141c3e2e5b747

**Comment by SethTisue** [comment]
@Philippus now we both know better for next time :-)

**Comment by Philippus** [comment]
let's not change it until after 2.13.0 final is out. :)

**Comment by SethTisue** [comment]
@Philippus since you don't do Twitter (afaict), fyi https://twitter.com/SethTisue/status/1133836388615544833
