### ISSUE TITLE
Release version 1.1.2 for scala 2.13.0

### ISSUE THREAD

**Issue by Philippus** [scala/scala-parser-combinators#216]
https://contributors.scala-lang.org/t/scala-2-13-0-release/3382/6

PR: https://github.com/scala/scala-parser-combinators/pull/215

tag: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2%232.13.0%238

build: https://travis-ci.org/scala/scala-parser-combinators/builds/542900844

**Comment by Philippus** [comment]
The build on Travis was successful

**Comment by SethTisue** [comment]
closed, released

now we watch https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2/

**Comment by Philippus** [comment]
and it's out!
