### ISSUE TITLE
drop util.parsing.json

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#221]
it would remain on 1.1.x, we'd drop it for 1.2.x

it's been deprecated for quite a while now

@Philippus wdyt?

part of the reason I'm interested is that it would make it easier to add a Dotty cross-build

**Comment by Philippus** [comment]
I think in the "Programming in Scala"-book you build a json parser yourself and not use this one right? In that case I think it's ok to drop it.

**Comment by SethTisue** [comment]
@bvenners wdyt?

**Comment by SethTisue** [comment]
(I don't think we need to wait on Bill for this. I think you are right about what the book recommends, and even if you happen to be wrong, we should still do the removal IMO)
