### ISSUE TITLE
shut down Gitter room?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#222]
it's not active, and it's one more thing to keep an eye on.

I suggest we delete the room and the reference in the repo readme

wdyt @Philippus?

**Comment by Philippus** [comment]
good idea!

**Comment by SethTisue** [comment]
I put an impending-shutdown notice in the room itself at https://gitter.im/scala/scala-parser-combinators?at=5d238d06cdb70805c95ec0ff

**Comment by SethTisue** [comment]
no more room! 💥

here's a log of what was there: https://gist.github.com/SethTisue/58d9f3e60b4797d9331c96ce695ca327
