### ISSUE TITLE
Add Dotty cross-build

### ISSUE THREAD

**Issue by Philippus** [scala/scala-parser-combinators#230]
As mentioned in https://github.com/scala/scala-parser-combinators/issues/221#issue-458575331, it would be neat to add cross-compilation to Dotty to this library.
To figure out how to do this, it might help to look at https://github.com/scala/scala-xml/pull/312, where this is done for the `scala-xml` library.

**Comment by SethTisue** [comment]
anyone watching this repo feel like attempting this...? I wouldn't expect the effort to hit any serious snags, it's just vanilla Scala 2 code with no dependencies besides JUnit

**Comment by SethTisue** [comment]
“good first issue” for someone wanting to dip their toes in the Dotty waters

**Comment by SethTisue** [comment]
@Philippus should we close this now?

**Comment by Philippus** [comment]
Closed in https://github.com/scala/scala-parser-combinators/pull/270
