### ISSUE TITLE
Add repNM for range repetition

### ISSUE THREAD

**Issue by pgrandjean** [scala/scala-parser-combinators#242]
This is a proposal to add operator `repNM` that repeats a parser in a `range(n, m)`. In other words, `repNM` would ensure that a parser is run at least `m` times and up to `n` times.

This proposal is a follow up on comments and code in [Stackoverflow](https://stackoverflow.com/questions/58360509/how-to-specify-a-range-of-repetitions-in-scalas-parser-combinators) by Jörg W Mittag.

I have some working code that I would like to submit in a PR, if it is OK to continue with this proposal.

**Comment by SethTisue** [comment]
I can't think of a reason this wouldn't be accepted

**Comment by pgrandjean** [comment]
PR #245 merged
