### ISSUE TITLE
Add Automatic-Module-Name to MANIFEST.INF

### ISSUE THREAD

**Issue by schrepfler** [scala/scala-parser-combinators#248]
In order to increase compatibility on JDK versions with modules consider adding Automatic-Module-Name in the MANIFEST.INF along the lines of https://github.com/akka/akka/pull/23960 or perhaps even implement properly the `module-info` descriptor.

**Comment by SethTisue** [comment]
best handled at https://github.com/scala/sbt-scala-module/issues/71
