### ISSUE TITLE
publish for Scala.js 1.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#265]

**Comment by SethTisue** [comment]
@eed3si9n asked how does back-publishing work in this repo?

@lrytz and I were just discussing this with @ashawley in the scala-xml repo: https://github.com/scala/scala-xml/pull/406#discussion_r378301931

there's two choices:
1) push a commit that removes the stuff you don't want published
2) go ahead and republish everything but then drop all of the staging repos except the one you actually wanted

1 is a bit more elegant and generates less atmospheric carbon. I sorta threw 2 out there, but 1 seems better

**Comment by SethTisue** [comment]
I opened https://github.com/olafurpg/sbt-ci-release/issues/102 to see if Olaf has an “official” position on this

**Comment by Philippus** [comment]
We did it like 1 last time for scala native. See https://github.com/scala/scala-parser-combinators/commit/373091b79055a854b8dfd53bae9f077f7201a8fe.

**Comment by SethTisue** [comment]
@Philippus looks like the discussion over on the sbt-ci-release ticket has settled down. want to try publishing, along the lines [Lukas suggests](https://github.com/olafurpg/sbt-ci-release/issues/102#issuecomment-586858984)?

**Comment by SethTisue** [comment]
if you have time to tackle it this weekend, great; otherwise, I can do it on Tuesday

**Comment by Philippus** [comment]
I've created a release tag here: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2%23scalajs100%238
and build is here: https://travis-ci.org/scala/scala-parser-combinators/builds/653772816?utm_source=github_status&utm_medium=notification

One thing to note is that I didn't touch the scala 2.12 and 2.13 versions so it is compiled against 2.12.8 and 2.13.0 (just like the other releases of version 1.1.2).

**Comment by Philippus** [comment]
I'm getting a "iv undefined" on the build. Seems to be something related to ssl.

**Comment by SethTisue** [comment]
@lrytz's fix for same issue in scala-xml repo: https://github.com/scala/scala-xml/pull/418

**Comment by lrytz** [comment]
I'll do the backport here as well.

**Comment by Philippus** [comment]
Thank you @lrytz , shall I delete the release tag?

**Comment by lrytz** [comment]
👍, we can re-do it once everything's ready

**Comment by lrytz** [comment]
With https://github.com/scala/scala-parser-combinators/pull/268 merged, releasing from the 1.1.x branch should work. If you want to re-release 1.1.2 for Scala.js 1.0, you need to create a commit that removes everything from the build matrix that's not needed, and tag that with `v1.1.2#some-suffix`.

**Comment by Philippus** [comment]
The tag is here: https://github.com/scala/scala-parser-combinators/releases/tag/v1.1.2%23scalajs100, and the build is green!

**Comment by eed3si9n** [comment]
Looks like these are in staging repositories on Sonatype OSS. I'll push these out to release.

**Comment by eed3si9n** [comment]
- https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_sjs1_2.11/1.1.2/
- https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_sjs1_2.12/1.1.2/
- https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_sjs1_2.13/1.1.2/
