### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#316]
@Philippus had you given this any thought...?

(thought prompted by https://github.com/scala/scala-parser-combinators/pull/234/)

**Comment by arashi01** [comment]
@Philippus, @SethTisue Any chance this can happen? (prompted by #270)

Ideally releasing against Dotty 3.0.0-M2 as well!

**Comment by SethTisue** [comment]
> Ideally releasing against Dotty 3.0.0-M2 as well!

I've opened a separate ticket for that: #334 

This ticket can be about broader 1.2.0 planning

**Comment by SethTisue** [comment]
Should it be 2.0.0, according to semantic versioning?

**Comment by SethTisue** [comment]
1.2.0-M1 is published

**Comment by SethTisue** [comment]
we're continuing to do 1.2.0-Mx releases as needed to support Scala 3 prereleases

in the absence of any other input or opinions about the future, I guess I'd be inclined to wait until Scala 3.0.0 final is released, then go 1.2.0-RC1 and then 1.2.0 final with whatever we have. there haven't been any complaints about the milestones

**Comment by Philippus** [comment]
In light of https://github.com/scala/sbt-scala-module/issues/111 I think we should also set a `VersionScheme` and make sure the next release complies with it. The next release will break binary compatibility.

**Comment by SethTisue** [comment]
maybe it's better to go RC1 _before_ Scala 3.0.0 final is released, as it seems unlikely that any further changes will land

**Comment by SethTisue** [comment]
Scala 3.0.0-RC2 is out. I will release 1.2.0-RC1 today.

**Comment by SethTisue** [comment]
1.2.0-RC1 is out

**Comment by SethTisue** [comment]
back published 1.2.0-RC1 for Scala 3.0.0-RC3

**Comment by xerial** [comment]
I think @SethTisue will release 1.2.0 now that Scala 3.0.0 is released. As always, thank you!

**Comment by SethTisue** [comment]
I'll try very hard to get to that today

**Comment by Philippus** [comment]
Should we make it 2.0.0 ?

**Comment by SethTisue** [comment]
> Should we make it 2.0.0 ?

I'd asked that above, back in December, but I can't remember what my thinking was at the time.  It should be 2.0 because we broke bincompat, is that right? (Sorry if we've been over this before, but I work in so many repos...)

**Comment by Philippus** [comment]
Yeah, we removed `scala.util.parsing.json` for one, so that's quite a big change already.

**Comment by SethTisue** [comment]
Looks like the planning is done and just the publishing remains: https://github.com/scala/scala-parser-combinators/issues/386

**Comment by xerial** [comment]
@SethTisue Thanks for the release! 

FYI. I found one issue with the major version change from 1.x to 2.x (e.g., sbt 1.5.x shows an error with dependency eviction https://github.com/twitter/util/pull/287), but I think the time will resolve this type of issue. A workaround is adding a setting like:

```scala
ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-parser-combinators" % "always"
```

**Comment by SethTisue** [comment]
Yeah, I think that's as expected.
