### ISSUE TITLE
Help on parsing regex using combinators

### ISSUE THREAD

**Issue by CEikermann** [scala/scala-parser-combinators#340]
Hey,

we are currently trying out to use the regex parser provided by this project.

We would like to the parse the following text: "Hello ABC<123>"
TermA should be "Hello ABC"
TermB should be 123

For the TermA we really need to match everything, because text like this is also possible "Hello ABC<111><123>"
This should produce: TermA = "Hello ABC<111>" and TermB = 123

Currently we are not able to make this working, as ".*" matches always the complete text.

Here our code example

```
  private def termA =  ".*".r 
  private def termB = literal("<") ~> "\\d+".r <~ literal(">") ^^ { _.toInt }

  val parser: Parser[....] = termA ~ termB ^^ {
    case valueA ~ valueB => 
      println(valueA)
      println(valueB)
  }
````

Any help or suggestion is welcome

Best regards,
Christian

**Comment by SethTisue** [comment]
in general in scala/* repos, we don't use our issue trackers for questions. maybe try https://users.scala-lang.org?
