### ISSUE TITLE
Build should declare a `versionScheme`

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#360]
as per https://scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html and discussion at scala/sbt-scala-module#111

**Comment by Philippus** [comment]
Can we start using `early-semver` from _now on_, or do we have to take the past into consideration?

**Comment by SethTisue** [comment]
uh, I'm not sure. off the top of my head my answer would be "from now on only".... but do you have a particular scenario or concern in mind?

**Comment by Philippus** [comment]
I think we can go with `"early-semver"` then, from now on. :)

**Comment by SethTisue** [comment]
fixed by #364
