### ISSUE TITLE
1.2.0-RC2 Native Empty Jar 

### ISSUE THREAD

**Issue by cheeseng** [scala/scala-parser-combinators#380]
1.2.0-RC2 Native Build Jar seems to be an empty jar: 

https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_native0.4_2.13/1.2.0-RC2/scala-parser-combinators_native0.4_2.13-1.2.0-RC2.jar

We're trying to use it from scalatest native build but it seems does not contain any useful class files.

Perhaps we're missing something?

**Comment by SethTisue** [comment]
@Philippus you seem to have touched the native build a number of times, is this something you're able to look into?

**Comment by Philippus** [comment]
Looks like this release was the last one with a non-empty jar: https://github.com/scala/scala-parser-combinators/releases/tag/v1.2.0-M1

**Comment by SethTisue** [comment]
jar under https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_native0.4_2.13/2.0.0/ seems normal sized
