### ISSUE TITLE
Unclosed multi-line comment not properly handled by StdLexical

### ISSUE THREAD

**Issue by martingd** [scala/scala-parser-combinators#399]
In scala.util.parsing.combinator.lexical.StdLexical handling of unclosed multi-line comments (`/* ... */`) does not seem to work as expected.

If an unclosed multi-line comment is encountered, instead of returning _one_ `ErrorToken(unclosed comment)`, _two_ `ErrorToken(illegal character)` tokens are returned (one for `/` and another for `*`) and scanning continues.

The issue is described in this comment.
https://github.com/scala/scala-parser-combinators/issues/397#issuecomment-858519419

@JakobLyngPetersen and I are working on a fix.

**Comment by SethTisue** [comment]
fixed by #403
