### ISSUE TITLE
.gitignore missing exclusions for recent sbt and for vscode/metals/bloop.

### ISSUE THREAD

**Issue by martingd** [scala/scala-parser-combinators#400]
The current .gitignore file is missing exclusions for recent sbt:

```
/.bsp/
```

and for vscode with metals and bloop:

```
.bloop/
/.metals/
/.vscode/
/project/**/metals.sbt
```

**Comment by Philippus** [comment]
fixed in https://github.com/scala/scala-parser-combinators/pull/404.
