### ISSUE TITLE
Dead link in docs/Getting_Started.md

### ISSUE THREAD

**Issue by pgimalac** [scala/scala-parser-combinators#421]
The link given in `docs/Getting_Started.md` for the documentation of `scala.util.parsing.combinator` (`http://www.scala-lang.org/files/archive/api/current/scala-parser-combinators/scala/util/parsing/combinator`) is dead.

**Comment by SethTisue** [comment]
a PR with a fix would be welcome. the correct link is in the README.

**Comment by pgimalac** [comment]
@SethTisue just to be sure is it this one `https://javadoc.io/page/org.scala-lang.modules/scala-parser-combinators_2.13/latest/scala/util/parsing/combinator/index.html` ?

**Comment by SethTisue** [comment]
yup
