### ISSUE TITLE
Incompatible type in overriding after upgrading to Scala 2.13

### ISSUE THREAD

**Issue by contra-bit** [scala/scala-parser-combinators#463]
Good day dear developers,

I would be very greafull if you could help me fix this type error.  Our reseach group is developing a parser for SysML and OCL, which generates C Code, with ACSL annotation. This is important, because the SysMLParsers are based on the OclParsers. (Extending the Lexer and the Parers). The Tokens for SysML do not extend our OclTokens.

![buy](https://user-images.githubusercontent.com/24410058/170756391-858e15ce-2526-4e34-a597-5e6a9239e6f5.png)
This Diagram shows the relationships of the differnet parsers, lexers and traits, which are relevant to this bug.

Our SysML parsers extends a lot of the functionality of the OclParser, this is why it uses the same token function. I think the problem is, that we use `scala.util.parsing.combinator.token.Tokens.Token`.   in our OclLTokens and `scala.util.combinatoir.parsing.lexical.Lexical` in the OclLexer
Booth Lexers provide `Tokens.Token`. 

The error is caused in the definition for the token function.
```scala
object SysMLLexer extends OclLexer {

  override def token = super.token

  def lineBreak = ('\r' ~ '\n' | '\n' | '\r')
}
```

Overriding the token Parser with `super.token`  in the SysMLLexer was no problem in Scala 2.12, now the types are illegal. 

I have created a [minimal example](https://github.com/contra-bit/minimal-specific) of our setup. The minimal example maintains the same inheritance and traits as our original project, but removes all depencies and only has one token, one delimiter one lexer and one parser function. It has two branches (scala [2,13](https://github.com/contra-bit/minimal-specific) and scala [2.12](https://github.com/contra-bit/minimal-specific/tree/feature/Scala2.12) , which aside of the scala version are identical. 

Running  `sbt run` will only succed in the Scala 2.12 Branch

Please tell me if this is a bug of Scala 2.13 or help me change the minimal example so that it can compile.

**Comment by joroKr21** [comment]
I'm not sure if it's a bug in Scala 2.13 but I also see some unexpected things in the code. Shouldn't `OclLexer` extends `OclTokens`? And in `OclTokens` you have `Delimiter` extending `OclTokens` (note the **S** in the end) - it should probably extend `OclToken` singular.

**Comment by contra-bit** [comment]
Hi,  @joroKr21  thanks alot for the feedback. Your PR, did solve all the issues in the minimal example, sadly not for the project.

Currently we are publishing the libraries we used in the project, so that it is possible for others to build it.
Atm we are struggling with `errorMessage`` defined in Scanners in Token. Which is most likely due to the fact, that
we use Lexical and Tokens in different places, thus we still have two different implementations of Token, 
which do not work together

I will post, again when it is possible for you guys (<3) to build it. If you are still in Berlin, I would be glad to invite you for a beer next month.
