### ISSUE TITLE
RegexParser parsed.successful breaks under java 1.8

### ISSUE THREAD

**Issue by paddymahoney** [scala/scala-parser-combinators#48]
We have a test that breaks under java 1.8 - it asserts that parsed.successful. Any suggestions on how to troubleshoot this issue?

**Comment by gourlaysama** [comment]
It is difficult to say anything without the code or a small reproduction. How is the parse result not successful: do you get a Failure, an Error, an exception?

**Comment by paddymahoney** [comment]
I found the cause of our issue. Not a RegexParser/parser combinator problem. 

Turns out that in java 8, the behavior of \v in a regex changes in a way that broke our test.
According to http://www.regexguru.com/, 
```In Java 4 to 7 \v is a character escape that matches only the vertical tab character. In Java 8 \v is a shorthand character class that matches any vertical whitespace, including the vertical tab. When upgrading to Java 8, make sure that any regexes that use \v still do what you want. Use \x0B or \cK to match just the vertical tab in any version of Java.```
In our case, not using \v was the ticket.
