### ISSUE TITLE
Publish for Scala-Native 0.5.0

### ISSUE THREAD

**Issue by catap** [scala/scala-parser-combinators#550]
This project is the last missed dependency which blocks scalatest.

Can you publish a versio for SN-0.5.0?

Thanks.

**Comment by SethTisue** [comment]
I’ll take care of this within the next 24-48 hours, unless another maintainer gets to it first

**Comment by Philippus** [comment]
Maybe we want to skip that one, and go for 5.1 immediately? https://github.com/scala/scala-parser-combinators/pull/551

**Comment by catap** [comment]
@Philippus both releases binary compatibility that means you may release from 0.5.0
or 0.5.1 without any differences

**Comment by ekrich** [comment]
Makes sense to just merge `0.5.1` anyway but not needed as mentioned.

**Comment by SethTisue** [comment]
* 0.5.1 upgrade merged
* https://github.com/scala/scala-parser-combinators/releases/tag/v2.4.0
* https://github.com/scala/scala-parser-combinators/actions/runs/8732472833
* https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_native0.5_3/
