### ISSUE TITLE
repository README should be clear about current maintenance status

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#60]
@gourlaysama, would you mind adding something to the front page that says you're handling community-based maintenance? I think someone looking at the current page might assume that the library is unmaintained, or that it's (primarily) maintained by the Scala team

**Comment by SethTisue** [comment]
awesome :-)

**Comment by gourlaysama** [comment]
BTW thanks for the awesome JIRA cleanup :-)
I'm looking into @biswanaths's script for importing things into Github now.

**Comment by biswanaths** [comment]
Gotcha @gourlaysama. 
Please do have a look at this https://github.com/scala/scala-xml/issues/62#issuecomment-123181866
Let me know if there are any issue or improvements you want to do. If you find satisfactory I can migrate the issue for scala-{parser-combinators | xml | swing }
