### ISSUE TITLE
community: open issues here for any significant old issue from JIRA

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#61]
today I closed all open parser combinator tickets in the [Scala JIRA](https://issues.scala-lang.org): 9010, 8080, 7483, 6520, 6491, 6464, 6067, 4929, 4002, 3212, 2420, 1566, 1547, 1482, 1229

many of these ought to become issues here in this repo on GitHub. interested community members are invited to open new issues for them here, with links in both directions

**Comment by SethTisue** [comment]
closing the interest of not having an issue that will likely be open forever.

#155 adds a reference from the README, as an alternate (IMO better) means of calling attention to the old issues.

**Comment by Philippus** [comment]
you can 'strike through' 9010 and 1547 as well I think

**Comment by SethTisue** [comment]
@Philippus GitHub now permits issues to be relocated from one repo to another within the same organization. shall we do it? (not sure if you have the needed permissions — if not, I could do it)

**Comment by Philippus** [comment]
I do have the option, but only for a subsett of the repos within the scala org, so if you could do it please do!

**Comment by SethTisue** [comment]
done!

readme change: #326

**Comment by SethTisue** [comment]
> I do have the option, but only for a subset of the repos within the scala org, so if you could do it please do

(fwiw, I didn't see scala-parser-combinators on the list either, and thought something was broken, but then a few minutes later I realized that if I typed the beginning of the repo name ("scala-parse") that made it appear)
