### ISSUE TITLE
Question: Recommended way to parse inline comments

### ISSUE THREAD

**Issue by TomasMikula** [scala/scala-parser-combinators#66]
Hi,

is there a canonical approach to parse inline comments (such as `/* comment */`) that can appear anywhere whitespace can appear, but instead of just ignoring them, still keep track of their source range for the purposes of syntax highlighting?

Thanks,
Tomas

**Comment by toddobryan-amazon** [comment]
I've just been thinking about this and couldn't come up with a good way to do it. Did you ever figure anything out?
