### ISSUE TITLE
Cut dependency on scala.collection.immutable.PagedSeq

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#71]
it is slated to be deprecated in Scala 2.12 and removed in Scala 2.13; see https://issues.scala-lang.org/browse/SI-9503

I think this is a desirable change for scala-parser-combinators anyway, since once you're using your own version, you'll be free to fix and change it without having to go through the process of getting changes made in the main Scala repo.

**Comment by SethTisue** [comment]
there is now a PR on this in the Scala repo: https://github.com/scala/scala/pull/4804

**Comment by hrj** [comment]
:+1: 

Since its deprecation in scala 2.11.x I get a dozen warnings in my project. Would be nice to have this fixed. Thanks!

**Comment by SethTisue** [comment]
Note that I'm assuming the source for PagedSeq would simply be copied into this repo.

**Comment by gourlaysama** [comment]
Fixed in #97.
