### ISSUE TITLE
`|||` should resolve a tie by choosing `this` parser rather than `q`

### ISSUE THREAD

**Issue by jeffrey-aguilera** [scala/scala-parser-combinators#72]
`if (next2.pos < next1.pos)` should be `if (next2.pos <= next1.pos)` (or equivalently `if (next1.pos >= next2.pos)`, which I feel is more readable and consistent with the specification that the ''longest'' is chosen.)

**Comment by toddobryan-amazon** [comment]
I think you're probably right. Based on the comments, you'd expect it to only use q0 if this parser consumed fewer characters, but with the code the way it is, it accepts q0 if they consume the same number.

Have you tried putting together a pull request with some test cases?

**Comment by hrj** [comment]
Possible to alter the comment rather than the code, in the interest of maintaining the current behaviour?

**Comment by SethTisue** [comment]
PR #166
