### ISSUE TITLE
Published version for Scala.js

### ISSUE THREAD

**Issue by paullepoulpe** [scala/scala-parser-combinators#85]
I see that you have support for Scala.js. But I can't find any published version for Scala.js.

**Comment by gourlaysama** [comment]
The Scala.js version used to be maintained separately under the `org.scala-js` organization. The only version available [appears to be v1.0.2][1]:

```
libraryDependencies += "org.scala-js" %%% "scala-parser-combinators" % "1.0.2"
```
Now that is has been merged in here, the Scala.js version will be immediately published with the jvm one, starting with the next release (1.0.5).

[1]: https://search.maven.org/#artifactdetails%7Corg.scala-js%7Cscala-parser-combinators_sjs0.6_2.11%7C1.0.2%7Cjar

**Comment by paullepoulpe** [comment]
Do you have an estimate of when that is going to happen ?

**Comment by gourlaysama** [comment]
I'll publish it shortly after Scala 2.12.0 is released, so it should be out within a month or so.

**Comment by SethTisue** [comment]
did this happen?

**Comment by alonsodomin** [comment]
Is there any update on this?

**Comment by SethTisue** [comment]
@gourlaysama do you need some help with this? I think we could find one or more volunteers

**Comment by SethTisue** [comment]
https://github.com/scala/scala-parser-combinators/releases/tag/v1.0.5 🎉
